name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Jans Rezepte'
        required: true
        default: 'rezepte'
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t $INPUT_IMAGE_NAME:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.imagename }}:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.inputs.imagename }}:latest
